config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	resources :candidates do
 		member do
 			post :vote
 		end
 	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	before_action :find_candidate, only:[:edit,:update,:destroy,:vote]

	def index
		@Candidates = Candidate.all
	end

	def new
		@Candidate = Candidate.new
	end

	def create
		@Candidate = Candidate.new(candidate_params)

		if @Candidate.save
			redirect_to candidates_path, notice:"Create new candidate success."
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @Candidate.update_attributes(candidate_params)
			redirect_to candidates_path,notice:"Update success!"
		else
			render :edit
		end
	end

	def destroy
		@Candidate.destroy
		redirect_to candidates_path,notice:"Candidate already deleted."
	end

	def vote
		@Candidate.increment(:votes)
		@Candidate.save
		redirect_to candidates_path,notice:"Thanks for vote!"
	end

	private
	def candidate_params
		params.require(:candidate).permit(:name, :age, :party, :politics)
	end

	def find_candidate
		@Candidate = Candidate.find_by(id:params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for @Candidate do |f| %>
	<%=f.label :name, "Name"%>
	<%=f.text_field :name %> <br>

	<%=f.label :age, "Age"%>
	<%=f.text_field :age %> <br>

	<%=f.label :party, "Party"%>
	<%=f.text_field :party %> <br>

	<%=f.label :politics, "Politics"%>
	<%=f.text_field :politics %> <br>

	<%=f.submit %>
<% end %>

<br>

app/views/candidates/edit.html.erb
<h1>Edit new candidate</h1>
<%=render "form"%>

<%=link_to 'Candidates list',candidates_path %>

app/views/candidates/index.html.erb
<h1>Candidates List</h1>
<%= link_to "Add new candidate",new_candidate_path%>

<table class="table">
	<thead>
		<tr>
			<td>Vote</td>
			<td>Name</td>
			<td>Party</td>
			<td>Politics</td>
			<td>Votes</td>
			<td>Action</td>
		</tr>
	</thead>

	<tbody>
		<% @Candidates.each do |candidate| %>
		<tr>
			<td><%= link_to "Vote" , vote_candidate_path(candidate), method: "post" , data:{ confirm: "Are you sure?"},class:"btn btn-danger btn-xs"%></td>
			<td><%= candidate.name %>(Age:<%= candidate.age %>)</td>
			<td><%= candidate.party %></td>
			<td><%= candidate.politics %></td>
			<td><%= candidate.votes %></td>
			<td>
			<%= link_to "Edit", edit_candidate_path(candidate) %>
			<%= link_to "Delete", candidate_path(candidate) , method: "delete" , data:{confirm:"Sure?"} %>
			</td>			
		</tr>
		<% end %>
	</tbody>

</table>

app/views/candidates/new.html.erb
<h1>Add new candidate</h1>
<%=render "form"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    <%= yield %>
    </div>
  </body>
</html>